NB_crm/urls.py
from django.contrib import admin
from django.urls import path,include
from crm import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('reg/', views.reg),
    path('crm/', include('crm.urls')),
    # path('user_list/', views.user_list),
]

crm/urls.py
from django.urls import path
from crm import views
urlpatterns = [

    #公户
    path('customer_list/',views.CustomerList.as_view(),name='customer_list'),
    # path('customer_list/',views.customer_list,name='customer_list'),
    #私户
    path('my_customer/',views.CustomerList.as_view(),name='my_customer'),
    # path('my_customer/',views.customer_list,name='my_customer'),
    #增加客户
    # path('customer/add/',views.add_customer,name='add_customer'),
    # #编辑客户
    # path('customer/edit/<int:nid>/',views.edit_customer,name='edit_customer'),
    path('customer/add/',views.customer,name='add_customer'),
    #编辑客户
    path('customer/edit/<int:nid>/',views.customer,name='edit_customer'),


]

crm/models.py
from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager,User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant',on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)
    class Meta:
        verbose_name = '客户列表'
        verbose_name_plural = '客户列表'
    def show_classes(self):
        # for i in self.class_list.all():
        #     print(i)
        return '|'.join([str(i) for i in self.class_list.all()])
    def show_status(self):
        '''
        (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))
        :return:
        '''
        color_dict = {
            'signed':'green',
            'unregistered':'red',
            'studying':'pink',
            'paid_in_full':'blue',
        }
        return mark_safe('<span style="background-color: {};color: white;padding: 4px">{}</span>'.format(color_dict[self.status],self.get_status_display()))




class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    class Meta:
        verbose_name = '校区表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级类型', blank=True,
                                  null=True)

    class Meta:
        verbose_name = '班级表'
        verbose_name_plural = verbose_name
        unique_together = ("course", "semester", 'campuses')
    def __str__(self):
        return "{}{}{}".format(self.get_course_display(),self.semester,self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户",on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records',on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称',on_delete=models.CASCADE)
    school = models.ForeignKey('Campuses',on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级",on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', verbose_name="客户",on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售",on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True,on_delete=models.CASCADE)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)

crm/views.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from django.contrib import auth
from crm.forms import RegForm,CustomerForm
from crm import models
from django.views import View
from django.db.models import Q
from utils.pager import PageInfo

def login(request):
    err_msg = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        obj = auth.authenticate(request, username=username, password=password)
        if obj:
            return redirect('/index/')
        err_msg = '用户名或密码错误'
    return render(request, 'login.html', {'err_msg': err_msg})

# 注册
def reg(request):
    form_obj = RegForm()
    if request.method == "POST":
        form_obj = RegForm(request.POST)
        if form_obj.is_valid():
            obj = form_obj.save()
            obj.set_password(obj.password)
            obj.save()
            return redirect('/login/')
            #方法一
           #  form_obj.cleaned_data.pop('re_password')
           #  models.UserProfile.objects.create_user(**form_obj.cleaned_data)
           #  return redirect('/login/')
           # #创建新用户

    return render(request,'reg.html',{'form_obj':form_obj})

#展示客户列表
# def customer_list(request):
#     if request.path_info == reverse('customer_list'):
#         all_customer = models.Customer.objects.filter(consultant__isnull=True)
#     else:
#         all_customer = models.Customer.objects.filter(consultant=request.user)
#     page = Pagination(request.GET.get('page'), request.path_info, all_customer.count())
#     return render(request, 'crm/customer_list.html',
#                   {"all_customer": all_customer[page.start:page.end], 'html_str': page.show_li})


#展示客户列表cbv
class CustomerList(View):
    def get(self,request):
        # print(request.path_info)
        # print(request.user)
        q = self.get_seach_contion(['name','qq'])
        if request.path_info == reverse('customer_list'):
            all_customer = models.Customer.objects.filter(q,consultant__isnull=True)
        else:
            all_customer = models.Customer.objects.filter(q,consultant=request.user)
            # print(request.user)
        page = PageInfo(request.GET.get('page'),all_customer.count(),request.path_info,5)
        return render(request, 'crm/customer_list.html',
                      {"all_customer": all_customer[page.start:page.end], 'html_str': page.pager})
    def post(self,request):
        #处理post提交的action数据
        # print(request.POST)
        action = request.POST.get('action')
        print(action)
        if not hasattr(self,action):
            return HttpResponse('非法操作')
        ret = getattr(self,action)()#获取action方法，如果存在加（）执行
        if ret:
            return ret
        return self.get(request)#post完之后在调用get返回customer_list
    def multi_apply(self):
        #公户变私户
        ids = self.request.POST.getlist('id')
        #方法1
        # models.Customer.objects.filter(id__in=ids).update(consultant =self.request.user)
        self.request.user.customers.add(*models.Customer.objects.filter(id__in=ids))
        # return HttpResponse('申请成功')
    def multi_pub(self):
        #私户变公户
        ids = self.request.POST.getlist('id')
        # 方法1
        # models.Customer.objects.filter(id__in=ids).update(consultant =None)
        #方法二
        self.request.user.customers.remove(*models.Customer.objects.filter(id__in=ids))
    def get_seach_contion(self,query_list):
        query = self.request.GET.get('query','')
        q= Q()
        q.connector = 'OR'
        for i in query_list:
            q.children.append(Q(('{}__contains'.format(i),query)))
        return q
        #Q( Q(qq_contains =query)| Q(name_contains =query))


#增加客户
# def add_customer(request):
#     form_obj = CustomerForm()
#     if request.method =="POST":
#         form_obj =CustomerForm(request.POST)
#         #d对数据进行校验
#         if form_obj.is_valid():
#             form_obj.save()
#             return redirect(reverse('customer_list'))
#
#     return  render(request,'crm/add_customer.html',{"form_obj":form_obj})
#
# #编辑客户
# def edit_customer(request,nid):
#     #根据id查出所需要编辑的客户
#     obj = models.Customer.objects.filter(id=nid).first()
#     form_obj = CustomerForm(instance=obj)#实例instance 把对象的内容实例
#     if request.method=="POST":
#         form_obj = CustomerForm(request.POST,instance=obj)
#         if form_obj.is_valid():
#             form_obj.save()
#             return redirect(reverse(customer_list))
#     return render(request,'crm/edit_customer.html',{'form_obj':form_obj})
#新增编辑客户
def customer(request,nid=None):
    obj = models.Customer.objects.filter(id=nid).first()
    form_obj = CustomerForm(instance=obj)#实例instance 把对象的内容实例
    if request.method=="POST":
        form_obj = CustomerForm(request.POST,instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('customer_list'))
    return render(request,'crm/customer.html',{'form_obj':form_obj,'nid':nid})

# users = [{'name':'yc{}'.format(i)} for i in range(1,302)]
# def user_list(request):
#     page =PageInfo(request.GET.get('page','1'),len(users),request.path_info,5,5)
#     return render(request,'user_list.html',{'data':users[page.start:page.end],'html_str':page.pager})

templates/crm/add_customer.html
{% extends 'layout.html' %}


{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">添加客户</div>

        <div class="panel-body">
            <div class="col-sm-8 col-sm-offset-2 ">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %} ">

                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label"> {{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block">
                            {{ field.errors.0 }}
                        </span>
                            </div>
                        </div>

                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </div>

                </form>

            </div>

        </div>


    </div>
{% endblock %}

templates/crm/customer.html
{% extends 'layout.html' %}


{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            {% if nid %}
                编辑用户
            {% else %}
                新增用户

            {% endif %}
        </div>

        <div class="panel-body">
            <div class="col-sm-8 col-sm-offset-2 ">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %} ">

                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label"> {{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block">
                            {{ field.errors.0 }}
                        </span>
                            </div>
                        </div>

                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </div>

                </form>

            </div>

        </div>


    </div>
{% endblock %}

templates/crm/customer_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        th, tr {
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Panel heading</div>
        <a href="{% url 'add_customer' %}" class="btn btn-primary btn-sm">添加</a>
        <div>
            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-primary">搜索 <i class="fa fa-search"></i> </button>
            </form>
        </div>
        <form action="" method="post" class="form-inline">
            {% csrf_token %}
            <select name="action" class="form-control"  >
                <option value="">请选择</option>
                <option value="multi_apply">放入私户</option>
                <option value="multi_pub">放入公户</option>
                <option value="multi_delte">删除</option>
            </select>
            <button class="btn btn-success btn-sm">提交</button>
            <table class="table table-condensed table-hover table-bordered">
            <thead>
            <tr>
                <th>请选择</th>
                <th>序号</th>
                <th>QQ</th>
{#                <th>QQ昵称</th>#}
                <th>姓名</th>
                <th>性别</th>
                <th>手机号</th>
                <th>客户来源</th>
                <th>咨询课程</th>
                <th>班级类型</th>
                <th>状态</th>
                <th>咨询日期</th>
{#                <th>最后跟进日期</th>#}
                <th>销售</th>
                <th>已报班级</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for customer in all_customer %}
                <tr>
                    <td><input type="checkbox" name="id" value="{{ customer.id }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ customer.qq }}</td>
{#                    <td>{{ customer.qq_name|default:'暂无' }}</td>#}
                    <td>{{ customer.name|default:'暂无' }}</td>
                    <td>{{ customer.get_sex_display }}</td>
                    <td>{{ customer.phone|default:'暂无' }}</td>
                    <td>{{ customer.get_source_display }}</td>
                    <td>{{ customer.course }}</td>
                    <td>{{ customer.get_class_type_display }}</td>
                    <td>
                        {{ customer.show_status }}

                    </td>
                    <td>{{ customer.date }}</td>
{#                    <td>{{ customer.last_consult_date }}</td>#}
                    <td>{{ customer.consultant }}</td>
                    <td>{{ customer.show_classes }}</td>
                    <td><a href="{% url 'edit_customer' customer.id %}"><i class="fa fa-edit fa-fw "></i></a></td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
        </form>


        <div style="text-align: center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ html_str}}
                </ul>
            </nav>
        </div>

    </div>
{% endblock %}

templates/crm/edit_customer.html
{% extends 'layout.html' %}


{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">编辑客户</div>

        <div class="panel-body">
            <div class="col-sm-8 col-sm-offset-2 ">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %} ">

                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label"> {{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block">
                            {{ field.errors.0 }}
                        </span>
                            </div>
                        </div>

                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </div>

                </form>

            </div>

        </div>


    </div>
{% endblock %}